datasetname: NASH
num_class: 3

random_seed: 7777
output: exp/encoder_com/nas/mean/uni/

model:
  name: mean
  feats_dim: 384

optimizer:
  lr: 2e-4
  epoch: 100
dataset:
  target: NAS-stage
  k_fold: 5
  root_dir: datasets/core/UNI-feature
  label_dir: datasets/core/labels.csv
  random: 7777
  bs: 1
  file_suffix: .csv # the "."