datasetname: NASH
num_class: 4

random_seed: 7777
output: exp/encoder_com/steatosis/mean/ours/

model:
  name: mean
  feats_dim: 1536

optimizer:
  lr: 2e-4
  epoch: 100
dataset:
  target: steatosis
  k_fold: 5
  root_dir: datasets/core/UNI-featrue-finetuned/
  label_dir: datasets/core/labels.csv
  random: 7777
  bs: 1
  file_suffix: .pt # the "."