datasetname: NASH
num_class: 4

random_seed: 7777
output: exp/encoder_com/inflam/abmil/conch/

model:
  name: abmil
  feats_dim: 512

optimizer:
  lr: 2e-4
  epoch: 100
dataset:
  target: inflammation
  k_fold: 5
  root_dir: datasets/CONCH-feature
  label_dir: datasets/labels.csv
  random: 7777
  bs: 1
  file_suffix: .csv # the "."