datasetname: NASH
num_class: 3

random_seed: 7777
output: exp/encoder_com/nas/mamba/giga/

model:
  name: mamba
  feats_dim: 1536

optimizer:
  lr: 2e-4
  epoch: 100
dataset:
  target: NAS-stage
  k_fold: 5
  root_dir: datasets/core/GIGA-feature
  label_dir: datasets/core/labels.csv
  random: 7777
  bs: 1
  file_suffix: .pt # the "."