datasetname: NASH
num_class: 4

random_seed: 7777
output: runs

model:
  milnet: abmil
  input_dim: 384

optimizer:
  lr: 2e-4
  epoch: 80
dataset:
  target: steatosis
  k_fold: 5
  root_dir: datasets/UNI-feature
  label_dir: datasets/labels.csv
  random: 7777
  bs: 1
  file_suffix: .csv # the "."