datasetname: NASH
num_class: 4

random_seed: 7777
output: exp/encoder_com/steatosis/abmil/uni/

model:
  name: abmil
  feats_dim: 384

optimizer:
  lr: 2e-4
  epoch: 100
dataset:
  target: steatosis
  k_fold: 5
  root_dir: datasets/UNI-feature
  label_dir: datasets/labels.csv
  random: 7777
  bs: 1
  file_suffix: .csv # the "."