datasetname: NASH
num_class: 4
softlabel: True
random_seed: 7777
output: exp/mil/nasc/steatosis/diff_soft_0.5

model:
  milnet: nasc
  feats_dim: 384

optimizer:
  # orloss: False
  loss: KL
  lr: 2e-4
  epoch: 80
dataset:
  sigma: 0.5
  target: steatosis
  k_fold: 5
  root_dir: datasets/core/UNI-feature
  label_dir: datasets/core/labels.csv
  random: 7777
  bs: 1
  file_suffix: .pt # the "."